


alert(`bem vindo ao meu programa!`)
let nome = prompt(`Qual seu nome?`)
alert(`Bem vindo ${nome}!`)
let idade = Number( prompt(`Qual sua idade?`))
let genero = prompt(`Qual o seu genero?`)
alert(`bem vindo ${nome}! Sua idade é ${idade}, e seu genero é ${genero}`)
console.log("=============");







//let numero1 = Number( prompt(`Adicione um numero:`))
//let numero2 = Number( prompt(`Adicione um segundo numero:`))





